#!/bin/bash

version_file=".version"

latest_git_tag="$1"
version=$(cat ${version_file})

parts=(${latest_git_tag//\./ })
major=${parts[0]}
minor=${parts[1]}
build=${parts[2]}

if [ "${major}.${minor}" == "$version" ]; then
  build=$(($build+1))
else
  parts=(${version//\./ })
  major=${parts[0]}
  minor=${parts[1]}
  build=0
fi

echo "version=${major}.${minor}.${build}" >> $GITHUB_OUTPUT