#!/bin/bash

#
# This script gets the latest git tag merged into the provided branch
#
# Usage: get_latest_tag <default_branch_name>
# Example: get_latest_tag origin/main
#

set -e

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <branch_name>"
    echo "Example: get_latest_tag origin/main"
    exit 1
fi

# Enable tracing mode if RUNNER_DEBUG is set to 1,
# so the script prints each command before executing it.
if [[ "$RUNNER_DEBUG" == "1" ]]; then
  set -x
fi

branch_name="$1"

git config --global --add safe.directory /github/workspace
git fetch --unshallow --tags 2>/dev/null || true
latest_tag=$(git tag --sort=-creatordate --merged ${branch_name} 2>/dev/null | head -n 1 || true)

set +x

echo $latest_tag