#!/bin/bash

#
# Pushes the provided tag to the remote repository.
# Only works with the default branch.
#
# Usage: push_tag <default_branch> <tag>
# Example: push_tag main v0.1.0
#

set -e

# Enable tracing mode if DEBUG_MODE is set to 1,
# so the script prints each command before executing it.
if [[ "$DEBUG_MODE" == "1" ]]; then
  set -x
fi

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <default_branch_name> <tag>"
    echo "Example: $0 main v0.1.0"
    exit 1
fi

default_branch="$1"
tag="$2"

if [ "$current_branch" == "$default_branch" ]; then
  git tag "$tag"
  git push origin "$tag"
else
  echo "Not on the main branch. Skipping tag push."
fi

set +x