name: Build the project

on: push

permissions:
  contents: write
  actions: write

jobs:
  lint-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Go version consistency
        run: ./.github/scripts/check_go_version_consistency

  build:
    runs-on: ubuntu-latest
    needs: [lint-project]
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run tests
        run: go test -v ./...

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == refs/heads/${{ github.event.repository.default_branch }}

    steps:
      - uses: actions/checkout@v4

      - name: Get latest git tag
        run: ./.github/scripts/bump_git_tag ${{ github.event.repository.default_branch }}