name: Build the project

on: push

jobs:
  lint-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Go version consistency
        run: ./.github/scripts/check_go_version_consistency

  build:
    runs-on: ubuntu-latest
    needs: [lint-project]
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run tests
        run: go test -v ./...

  create-git-tag:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)

    steps:
      - uses: actions/checkout@v4

      - name: Get latest git tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: latest-tag

      - name: Bump the version
        run: ./.github/scripts/bump_version ${{ steps.latest-tag.outputs.tag }}
        id: version

      - name: Push the new version
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.version.outputs.content }}