name: Build the project

on: push

permissions:
  contents: write
  actions: write

jobs:
  lint-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Go version consistency
        run: ./.github/scripts/check_go_version_consistency

  build:
    runs-on: ubuntu-latest
    needs: [lint-project]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Run tests
        run: go test -v ./...

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)

    steps:
      - uses: actions/checkout@v4

      - name: Get the latest tag pushed to the default branch
        id: latest_tag
        run: |
          TAG=$(./.github/scripts/get_latest_tag "origin/${{ github.event.repository.default_branch }}")
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Bump the version according to SemVer and the .version file
        id: bump_version
        run: |
          VERSION=$(./.github/scripts/bump_version ${{ steps.latest_tag.outputs.tag }})
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Push the new version as a new tag
        run: ./.github/scripts/push_tag ${{ steps.bump_version.outputs.version }}