name: Build the project

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [lint-project]
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run tests
        run: go test -v ./...