name: Project Linter

on: push

jobs:
  lint-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Go version consistency
        run: ./.github/scripts/check_go_version_consistency